export const ColumnasIngreso = [
    { field: 'id', header: 'ID' },
    { field: 'fecha', header: 'Fecha' },
    { field: 'guia_remision', header: 'Guia Remisión' },
    { field: 'tipo_operacion', header: 'Tipo Operación' },
    { field: 'tipo_cp', header: 'Tipo de CP' },
    { field: 'documento', header: 'Documento' },
    { field: 'orden_compra', header: 'Orden de Compra' },
    { field: 'codigo_proveedor', header: 'Codigo Proveedor' },
    { field: 'proveedor', header: 'Proveedor' },
    { field: 'SKU', header: 'SKU' },
    { field: 'familia', header: 'Familia' },
    { field: 'sub_familia', header: 'Sub Familia' },
    { field: 'articulo', header: 'Articulo' },
    { field: 'marca', header: 'Marca' },
    { field: 'precio_dolares', header: 'Precio Dolares' },
    { field: 'precio_soles', header: 'Precio Soles' },
    { field: 'stock_logico', header: 'Stock Lógico' },
    { field: 'unidad_medida', header: 'UM' },
    { field: 'ingreso', header: 'Ingreso' },
    { field: 'precio_unitario_soles', header: 'Precio Unitario Soles' },
    { field: 'precio_total_soles', header: 'Precio Total Soles' },
    { field: 'precio_unitario_dolares', header: 'Precio Unitario Dolares' },
    { field: 'precio_total_dolares', header: 'Precio Total Dolares' },
    { field: 'observaciones', header: 'Observaciones' },
]