export const ColumnasPeronal = [
    { field: 'numero_documento', header: 'Documento' },
    { field: 'fecha_nacimiento', header: 'Fecha Nacimiento' },
    { field: 'nombre', header: 'Nombre' },
    { field: 'apellido', header: 'Apellidos' },
    { field: 'gmail', header: 'Gmail' },    
    { field: 'fecha_ingreso', header: 'Fecha Ingreso' },
    { field: 'fecha_salida', header: 'Fecha Salida' },
    { field: 'inicio_contrato', header: 'Inicio Contrato' },
    { field: 'fin_contrato', header: 'Fin Contrato' },
    { field: 'area', header: 'Área' },
    { field: 'cargo', header: 'Cargo' },
    { field: 'ingreso_planilla', header: 'Ingreso Planilla' },
    { field: 'planilla', header: 'Planilla' },
    { field: 'sueldo_planilla', header: 'Sueldo Planilla' },
    { field: 'sueldo_real', header: 'Sueldo Real' },
    { field: 'fecha_alta', header: 'Fecha Alta' },
    { field: 'fecha_baja', header: 'Fecha Baja' },
];
